#! /bin/bash

java_prefix="/usr/lib/jvm/default-java"

$BOOST_ROOT/bjam eraser_inst variant=debug
$java_prefix/bin/javac src/eraser/Proxy.java -d bin
classpath=$eraser/inputs/inc
class=Inc
args=$1
rm -f dump out *.log backtrace stdout

( cd inputs/inc/inc ; $java_prefix/bin/javac *.java )
( cd inputs/inc ; $java_prefix/bin/javac *.java)

( $java_prefix/bin/java -Xcheck:jni -Xloggc:gc.log -verbose:jni -agentpath:./bin/liberaser.so=--log-level=$2 -Xbootclasspath/a:./bin -cp $classpath $class $args > stdout )>& out
#gdb --args java -agentpath:./bin/liberaser.so=--log-level=1 -Xbootclasspath/a:./bin -cp $classpath $class $args
#$java_prefix/bin/jdb  -J-agentpath:./bin/agent.so -J-Xbootclasspath/a:./bin -classpath $classpath $class $args
