#! /bin/bash

$BOOST_ROOT/bjam eraser_inst
javac src/eraser/Proxy.java -d bin
classpath=$eraser/inputs/inc
class=Inc
args="4 2 2"
rm -f out
java -Dcom.sun.management.jmxremote  -agentpath:./bin/liberaser.so -Xbootclasspath/a:./bin -cp $classpath $class $args >& out
#java -agentpath:./bin/liberaser.so -Xbootclasspath/a:./bin -cp $eraser/inputs/trivial Inc 1 10 true

#jdb  -J-agentpath:./bin/agent.so -J-Xbootclasspath/a:./bin -classpath $classpath $class $args
