#! /bin/bash

java_prefix="/usr/lib/jvm/default-java"

$BOOST_ROOT/bjam eraser_inst variant=debug define=SHOW_PARSED_ARGS
$java_prefix/bin/javac src/eraser/Proxy.java -d bin
classpath=$eraser/inputs/ex1
class=ex1.Ex1
args="inputs/ex1/samples/ak47.lif 8 8 100 200 200"
rm -f dump out *.log backtrace stdout

$java_prefix/bin/java -Xcheck:jni -Xprof -agentpath:./bin/liberaser.so=--log-level=$1,--obj-filter='Lex1/Cell',--thread-filter='Lex1/\\w+;' -Xbootclasspath/a:./bin -cp $classpath $class $args > out

#gdb --args java -agentpath:./bin/liberaser.so=--log-level=1 -Xbootclasspath/a:./bin -cp $classpath $class $args
#$java_prefix/bin/jdb  -J-agentpath:./bin/agent.so -J-Xbootclasspath/a:./bin -classpath $classpath $class $args
