#! /bin/bash

java_prefix="/usr/lib/jvm/default-java"

classpath=$eraser/inputs/inc
class=Inc
args="2 5 2"
for i in {1..500}
do
        rm -f dump out backtrace stdout
        ( $java_prefix/bin/java -Xcheck:jni -agentpath:./bin/liberaser.so=--log-level=1 -Xbootclasspath/a:./bin -cp $classpath $class $args > stdout )>& out
        #$java_prefix/bin/java -Xcheck:jni -agentpath:./bin/liberaser.so=--log-level=1 -Xbootclasspath/a:./bin -cp $classpath $class $args
        echo "------------------------------------------------------------------"
        echo $i
        cat stdout
        cat backtrace
done
#java -agentpath:./bin/liberaser.so -Xbootclasspath/a:./bin -cp $eraser/inputs/trivial Inc 1 10 true
#jdb  -J-agentpath:./bin/agent.so -J-Xbootclasspath/a:./bin -classpath $classpath $class $args
